spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/qq_news
    username: root
    password: 123456

  jpa:
    show-sql: true
    database: mysql